"""lifecycle indexes and question uniqueness

Revision ID: 37f36c5b3cd4
Revises: 0650a4f7cf24
Create Date: 2026-09-24 09:07:44.049749
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37f36c5b3cd4'
down_revision: Union[str, None] = '0650a4f7cf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_clarifying_questions_task_id_order', 'clarifying_questions', ['task_id', 'order'])
    op.create_index(op.f('ix_proposals_created_at'), 'proposals', ['created_at'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_index(op.f('ix_proposals_task_id'), 'proposals', ['task_id'], unique=False)
    op.create_index(op.f('ix_proposals_team_id'), 'proposals', ['team_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_rating_score'), 'tasks', ['rating_score'], unique=False)
    op.create_index(op.f('ix_tasks_readiness_level'), 'tasks', ['readiness_level'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_readiness_level'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_rating_score'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_proposals_team_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_task_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_created_at'), table_name='proposals')
    op.drop_constraint('uq_clarifying_questions_task_id_order', 'clarifying_questions', type_='unique')
    # ### end Alembic commands ###
