"""add ownership domain

Revision ID: 54841236897c
Revises: 37f36c5b3cd4
Create Date: 2026-09-24 11:16:04.048681
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '54841236897c'
down_revision: Union[str, None] = '37f36c5b3cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='organizationmemberrole', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_members_org_user')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='teammemberrole', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_team_user')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.add_column('proposals', sa.Column('submitted_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_proposals_submitted_by_user_id'), 'proposals', ['submitted_by_user_id'], unique=False)
    op.drop_constraint(op.f('proposals_task_id_fkey'), 'proposals', type_='foreignkey')
    op.create_foreign_key('fk_proposals_task_id_tasks', 'proposals', 'tasks', ['task_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('proposals_team_id_fkey'), 'proposals', type_='foreignkey')
    op.create_foreign_key('fk_proposals_submitted_by_user_id_users', 'proposals', 'users', ['submitted_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_proposals_team_id_teams', 'proposals', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    op.add_column('tasks', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_created_by_user_id'), 'tasks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_foreign_key('fk_tasks_organization_id_organizations', 'tasks', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_tasks_created_by_user_id_users', 'tasks', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_created_by_user_id_users', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_tasks_organization_id_organizations', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by_user_id'), table_name='tasks')
    op.drop_column('tasks', 'created_by_user_id')
    op.drop_column('tasks', 'organization_id')
    op.drop_constraint('fk_proposals_team_id_teams', 'proposals', type_='foreignkey')
    op.drop_constraint('fk_proposals_submitted_by_user_id_users', 'proposals', type_='foreignkey')
    op.drop_constraint('fk_proposals_task_id_tasks', 'proposals', type_='foreignkey')
    op.create_foreign_key(op.f('proposals_task_id_fkey'), 'proposals', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('proposals_team_id_fkey'), 'proposals', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_proposals_submitted_by_user_id'), table_name='proposals')
    op.drop_column('proposals', 'submitted_by_user_id')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
